### ISSUE TITLE
FileList: delete file

### ISSUE THREAD

**Issue by sansculotte** [sansculotte/droptrack#39]
trashcan (or similar) icon in each row to delete file

**Comment by x75** [comment]
i think this quite important for practical reasons. just got a request, even to wipe entire sessions to get clean slate

**Comment by sansculotte** [comment]
> i think this quite important for practical reasons.

certainly is.

> just got a request, even to wipe entire sessions to get clean slate

see what you mean, but sessions ... that would be an entirely new set of features.
