### ISSUE TITLE
downloaded autoedit result is called "wav.wav"

### ISSUE THREAD

**Issue by x75** [sansculotte/droptrack#49]

**Comment by x75** [comment]
downloaded autoedit result top-level json is missing .json filename suffix

**Comment by x75** [comment]
just tested this. now the .wav filename seems OK. different issue though, wav file download has a long delay between clicking the download link and getting the "save to" dialog

**Comment by sansculotte** [comment]
https://github.com/sansculotte/droptrack/pull/51 should fix this.
