### ISSUE TITLE
Number of segments input won't allow first digit other than 2. 

### ISSUE THREAD

**Issue by IanMFraser** [sansculotte/droptrack#53]
Mentioned this to Oswald. Number of segments can only start with the number 2. Maybe this is clear with a little documentation?

**Comment by sansculotte** [comment]
i can't reproduce this. neither the UI nor smp_audio prevents me from running autoedit with numsegs=10 or numsegs=1
i am assuming this is not an UI issue?

**Comment by IanMFraser** [comment]
I think the issue actually lies in that the input field cannot be empty. If I have 120 segments and try to delete characters to change it to 300 segments, the UI will not allow me to delete the 1. Selecting all and typing a new number works. Selecting all and delete does not.

**Comment by sansculotte** [comment]
i see. thanks for the clarification.
