### ISSUE TITLE
data/upload directory is in git and overwrites symlink to data store

### ISSUE THREAD

**Issue by x75** [sansculotte/droptrack#67]
moved the data to large storage volume between the last two deploys and created symlink to new directory on data/upload

today's deploy returned a 404 on /files because the symlink was removed and empty directory created

**Comment by sansculotte** [comment]
You can set the path to your UPLOAD_DIR in the configuration file. config.py.dist even has an example, where in ProductionConfig UPLOAD_DIR is set to /opt/droptrack/data/upload, which the in ansible playbook is scripted to create.
